version: '3.9'

services:
  webapp:
    build: ./
    image: choreganise-webapp:local
    ports:
      - '80:3000'
    volumes:
      - './package.json:/home/node/package.json'
      - './public:/home/node/public'
      - './src:/home/node/src'
